---
- name: Deploy Flipkart
  hosts: webservers
  become: yes

  tasks:

    - name: Install packages
      yum:
        name: httpd 
        state: present
    
    - name: Ensure httpd is running
      service:
        name: httpd 
        state: started
        enabled: yes

    - name: Install Git
      yum:
        name: git
        state: present

    - name: Clone Flipkart
      git:
         repo: "https://github.com/Msocial123/Flipkart-Clone.git"
         dest: "/home/ansible/Flipkart-Clone"
         version: main
         force: yes

    - name: Copy application
      copy:
         src: "/home/ansible/Flipkart-Clone"
         dest: "/var/www/html/"
         owner: apache
         group: apache
         mode: '0755'
         remote_src: yes

    - name: Set correct Permission
      file: 
         path: /var/www/html/
         owner: apache
         group: apache
         recurse: yes
