---
- name: Deploy Flip[kart
  hosts: webservers
  become: yes

  tasks:

    - name: Install packages
      action: yum pkg=httpd state=present

    - name: Install packages
      action: yum pkg=git state=present
    
    - name: Ensure httpd is running
      action: service name=httpd state=started

    - name: Clone Flipkart
      git:
         repo: "https://github.com/Msocial123/Flipkart-Clone.git"
         dest: "/home/ansible/Flipkart-Clone"
         version: master
         force: yes
    - name: Copy application
      copy:
         src: "/home/ansible/Flipkart-Clone"
         dest: "/var/www/html/"
         owner: apache
         group: apache
         mode: '0755'
         remote_src: yes

    - name: Set correct Permission
      file: 
         path: /var/www/html/
         owner: apache
         group: apache
         recurse: yes
