---
- hosts: webservers
  user: ansible
  become: true
  connection: ssh

  tasks:

    - name: Install Git on Host Machines
      action: yum pkg=git state=present

    - name: Install docker on Host Machines
      action: yum pkg=docke state=present
      ignore_errors: yes

    - name: Start Docker Server on Host Machines
      action: service name=docker state=started

    - name: Start Docker Server on Host Machines
      action: service name=docker state=stopped

    - name: Start Docker Server on Host Machines
      action: service name=docker state=started

    - name: Install java on Host Machines
      action: yum pkg=java-17-amazon-corretto state=present

    - name: Install python on Host Machines
      action: yum pkg=python3 state=present
    
    - name: Install httpd on Host Machines
      action: yum pkg=httpd  state=present

    - name: Install mysql on Host Machines
      action: yum pkg=mysql  state=present


    - name: Start httpd Server on Host Machines
      action: service name=httpd state=started

    - name: Start httpd Server on Host Machines
      action: service name=httpd state=stopped

    - name: Start httpd Server on Host Machines
      action: service name=httpd state=restarted

    
    
